detect_lane:
  ros__parameters:
    birdView:
      bottom_x: 350
      bottom_y: 240
      top_x: 90
      top_y: -60
    mask_lane:
      expected_value: 2500.0
    hsv_model:
      white:
        hue_h: 41
        hue_l: 0
        saturation_h: 18
        saturation_l: 0
        value_h: 255
        value_l: 191
      yellow:
        hue_h: 37
        hue_l: 26
        saturation_h: 255
        saturation_l: 212
        value_h: 255
        value_l: 119
    show_image: true
